name: Update Gradle Wrapper and validate
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.16
      - name: Gradle validation
        uses: gradle/wrapper-validation-action@v1.0.4
